In [1]:
print("Hola mundo")

Hola mundo

In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data_febrero = pd.read_excel("../data/raw/VENTAS_FEBRERO2026.xlsx", sheet_name="VTA_ACT")
data_marzo = pd.read_excel("../data/raw/VENTAS_MARZO2026.xlsx", sheet_name="Sheet1")
familias_productos = pd.read_excel("../data/raw/VENTAS_FEBRERO2026.xlsx", sheet_name="Sheet1")

In [86]:
data_febrero.head()

,REF. DE VENTA,FOLIO DE ORDEN,SUCURSAL,ABREVIATURA,FECHA,HORA,FAMILIA,PRODUCTO,CANTIDAD,SUBTOTAL,Unnamed: 10
0,Tienda 7 SANTA LUCIA/154162,Orden 23193-001-0001,Tienda 7 SANTA LUCIA (SANTA LUCIA),SLU,2026-02-01,06:24:28,POSTRE INDIVIDUAL,[PTEENS0060] PT - RATON DE CHOCOLATE,1.0,25.0,NaN
1,Tienda 7 SANTA LUCIA/154162,Orden 23193-001-0001,Tienda 7 SANTA LUCIA (SANTA LUCIA),SLU,2026-02-01,06:24:28,POSTRE INDIVIDUAL,[PTEENS0061] PT - TARTALETA DE FRUTAS,1.0,50.0,NaN
2,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL (FERROCARRIL),FER,2026-02-01,06:42:44,GALLETAS,[PTEENS0070] PT - DOMO DE BURBUJA,1.0,120.0,NaN
3,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL (FERROCARRIL),FER,2026-02-01,06:42:44,GALLETAS,[PTEENS0070] PT - DOMO DE BURBUJA,1.0,120.0,NaN
4,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL (FERROCARRIL),FER,2026-02-01,06:42:44,DESC.GALLETAS,Combo burbuja,1.0,-20.0,NaN

In [102]:
data_febrero["SUCURSAL"] = data_febrero["SUCURSAL"].str.split("(").str[0].str.strip()

In [103]:
data_febrero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367672 entries, 0 to 367671
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   REF. DE VENTA   367672 non-null  object
 1   FOLIO DE ORDEN  367672 non-null  object
 2   SUCURSAL        367672 non-null  object
 3   ABREVIATURA     367672 non-null  object
 4   FECHA           367672 non-null  datetime64[ns]
 5   HORA            367672 non-null  object
 6   FAMILIA         367672 non-null  object
 7   PRODUCTO        367672 non-null  object
 8   CANTIDAD        367672 non-null  float64
 9   SUBTOTAL        367672 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 28.1+ MB

In [104]:
data_febrero.describe()

                               FECHA       CANTIDAD       SUBTOTAL
count                         367672  367672.000000  367672.000000
mean   2026-02-14 08:28:01.524837120       1.690017      68.845483
min              2026-02-01 00:00:00    -100.000000   -2798.500000
25%              2026-02-07 00:00:00       1.000000      15.000000
50%              2026-02-14 00:00:00       1.000000      35.000000
75%              2026-02-21 00:00:00       1.000000      65.000000
max              2026-02-28 00:00:00     600.000000    7110.000000
std                              NaN       3.428189     118.011457

In [105]:
data_febrero.drop(columns=["Unnamed: 10"], inplace=True)

KeyError: "['Unnamed: 10'] not found in axis"

In [106]:
data_marzo.head()

,SUCURSAL,REF. DE VENTA,FOLIO DE ORDEN,FECHA,HORA,PRODUCTO,CANTIDAD,SUBTOTAL
0,Tienda 7 SANTA LUCIA,Tienda 7 SANTA LUCIA/160542,Orden 23976-001-0001,2026-03-01 06:39:03,06:39:03,[PTEENS0053] PT - EMPANADA DE ATUN,6,210.0
1,Tienda 7 SANTA LUCIA,Tienda 7 SANTA LUCIA/160542,Orden 23976-001-0001,2026-03-01 06:39:03,06:39:03,[EMPVAR033] VASO CAFÉ 12 OZ,1,40.0
2,Tienda 7 SANTA LUCIA,Tienda 7 SANTA LUCIA/160542,Orden 23976-001-0001,2026-03-01 06:39:03,06:39:03,[PTEENS0303] PT - DOMO MINI OREJITAS,1,120.0
3,Tienda 7 SANTA LUCIA,Tienda 7 SANTA LUCIA/160542,Orden 23976-001-0001,2026-03-01 06:39:03,06:39:03,[PTEENS0303] PT - DOMO MINI OREJITAS,1,120.0
4,Tienda 7 SANTA LUCIA,Tienda 7 SANTA LUCIA/160542,Orden 23976-001-0001,2026-03-01 06:39:03,06:39:03,Combo burbuja,1,-20.0

In [133]:
abreviaciones = data_febrero["ABREVIATURA"].unique()

sucursales = data_febrero["SUCURSAL"].unique()

In [108]:
abrev_sucursal = dict(zip(sucursales, abreviaciones))

In [112]:
data_marzo["ABREVIATURA"] = data_marzo["SUCURSAL"].apply(lambda x: abrev_sucursal[x])

In [119]:
data_marzo.sample(3)

,SUCURSAL,REF. DE VENTA,FOLIO DE ORDEN,FECHA,HORA,PRODUCTO,CANTIDAD,SUBTOTAL,ABREVIATURA
11774,Tienda 15 PLAZA BELLA,Tienda 15 PLAZA BELLA/213017,Orden 23990-005-0316,2026-03-01 19:19:04,19:19:04,[10100102019] PT - PASTEL CRUNCH,1,375.0,PBE
290,Tienda 16 TLACOLULA,Tienda 16 TLACOLULA/193475,Orden 23984-001-0005,2026-03-01 08:30:07,08:30:08,PANADERIA 5 X 6,1,-15.0,TLA
10969,Tienda 12 REFORMA,Tienda 12 REFORMA/153217,Orden 23989-014-0148,2026-03-01 18:50:39,18:50:40,[PTEENS0061] PT - TARTALETA DE FRUTAS,1,50.0,REF

In [134]:
data_marzo["PRODUCTO"]

0          [PTEENS0053] PT - EMPANADA DE ATUN
1                 [EMPVAR033] VASO CAFÉ 12 OZ
2        [PTEENS0303] PT - DOMO MINI OREJITAS
3        [PTEENS0303] PT - DOMO MINI OREJITAS
4                               Combo burbuja
                         ...
14532                           BOLILLO 2 X 1
14533               [PTEENS0188] PT - BOLILLO
14534        [PTEHOR002] PT - CONCHA VAINILLA
14535       [PTEHOR001] PT - CONCHA CHOCOLATE
14536                         2 x 1 Panaderia
Name: PRODUCTO, Length: 14537, dtype: object

In [140]:
data_marzo = pd.merge(data_marzo, familias_productos, on="PRODUCTO", how="left")

In [148]:
data_marzo = data_marzo[data_febrero.columns]

In [150]:
data_unificada = pd.concat([data_febrero, data_marzo])

In [155]:
data_unificada

,REF. DE VENTA,FOLIO DE ORDEN,SUCURSAL,ABREVIATURA,FECHA,HORA,FAMILIA,PRODUCTO,CANTIDAD,SUBTOTAL
0,Tienda 7 SANTA LUCIA/154162,Orden 23193-001-0001,Tienda 7 SANTA LUCIA,SLU,2026-02-01 00:00:00,06:24:28,POSTRE INDIVIDUAL,[PTEENS0060] PT - RATON DE CHOCOLATE,1.0,25.0
1,Tienda 7 SANTA LUCIA/154162,Orden 23193-001-0001,Tienda 7 SANTA LUCIA,SLU,2026-02-01 00:00:00,06:24:28,POSTRE INDIVIDUAL,[PTEENS0061] PT - TARTALETA DE FRUTAS,1.0,50.0
2,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL,FER,2026-02-01 00:00:00,06:42:44,GALLETAS,[PTEENS0070] PT - DOMO DE BURBUJA,1.0,120.0
3,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL,FER,2026-02-01 00:00:00,06:42:44,GALLETAS,[PTEENS0070] PT - DOMO DE BURBUJA,1.0,120.0
4,Tienda 19 FERROCARRIL/162995,Orden 23192-001-0001,Tienda 19 FERROCARRIL,FER,2026-02-01 00:00:00,06:42:44,DESC.GALLETAS,Combo burbuja,1.0,-20.0
...,...,...,...,...,...,...,...,...,...,...
14622,Tienda 1 GONZALEZ ORTEGA/237247,Orden 23987-004-0265,Tienda 1 GONZALEZ ORTEGA,QMU,2026-03-01 21:05:07,21:05:07,DESC.PANADERIA,BOLILLO 2 X 1,1.0,-4.0
14623,Tienda 13 VOLCANES/119266,Orden 23988-007-0209,Tienda 13 VOLCANES,VOL,2026-03-01 21:06:40,21:06:53,PANADERIA,[PTEENS0188] PT - BOLILLO,1.0,4.0
14624,Tienda 13 VOLCANES/119267,Orden 23988-007-0210,Tienda 13 VOLCANES,VOL,2026-03-01 21:11:42,21:11:50,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,2.0,30.0
14625,Tienda 13 VOLCANES/119267,Orden 23988-007-0210,Tienda 13 VOLCANES,VOL,2026-03-01 21:11:42,21:11:50,PANADERIA,[PTEHOR001] PT - CONCHA CHOCOLATE,2.0,30.0
14626,Tienda 13 VOLCANES/119267,Orden 23988-007-0210,Tienda 13 VOLCANES,VOL,2026-03-01 21:11:42,21:11:50,DESC.PANADERIA,2 x 1 Panaderia,1.0,-30.0

In [152]:
data_unificada[data_unificada["PRODUCTO"] == "[PTEHOR002] PT - CONCHA VAINILLA"]

,REF. DE VENTA,FOLIO DE ORDEN,SUCURSAL,ABREVIATURA,FECHA,HORA,FAMILIA,PRODUCTO,CANTIDAD,SUBTOTAL
6,Tienda 7 SANTA LUCIA/154163,Orden 23193-001-0002,Tienda 7 SANTA LUCIA,SLU,2026-02-01 00:00:00,07:04:15,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
23,Tienda 8 TACUBA/140513,Orden 23197-001-0001,Tienda 8 TACUBA,TAC,2026-02-01 00:00:00,07:16:33,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
56,Tienda 8 TACUBA/140515,Orden 23197-001-0003,Tienda 8 TACUBA,TAC,2026-02-01 00:00:00,07:39:22,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
121,Tienda 2 INDEPENDENCIA/181537,Orden 23194-001-0007,Tienda 2 INDEPENDENCIA,IND,2026-02-01 00:00:00,08:03:09,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,3.0,45.0
144,Tienda 7 SANTA LUCIA/154170,Orden 23193-001-0009,Tienda 7 SANTA LUCIA,SLU,2026-02-01 00:00:00,08:07:01,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,2.0,30.0
...,...,...,...,...,...,...,...,...,...,...
14538,Tienda 19 FERROCARRIL/169346,Orden 23981-002-0241,Tienda 19 FERROCARRIL,FER,2026-03-01 20:56:55,20:56:55,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
14589,Tienda 9 TULE/143128,Orden 23997-002-0230,Tienda 9 TULE,TUL,2026-03-01 21:00:57,21:01:01,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,2.0,30.0
14606,Tienda 23 PERIFERICO/95952,Orden 24001-001-0139,Tienda 23 PERIFERICO,PER,2026-03-01 21:03:15,21:03:15,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
14611,Tienda 18 CAMINO NACIONAL/111160,Orden 24000-003-0154,Tienda 18 CAMINO NACIONAL,CNL,2026-03-01 21:03:48,21:03:48,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,1.0,15.0
14624,Tienda 13 VOLCANES/119267,Orden 23988-007-0210,Tienda 13 VOLCANES,VOL,2026-03-01 21:11:42,21:11:50,PANADERIA,[PTEHOR002] PT - CONCHA VAINILLA,2.0,30.0

In [ ]:
data_conchas_vainilla =